I 03-17 18:35:47 controller.py:59] DAG:
I 03-17 18:35:47 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 18:35:47 controller.py:59]   resources: AWS(cpus=4, {'L4': 1}, region=ap-northeast-2)]
I 03-17 18:35:47 controller.py:195] Submitted managed job 127 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-18-35-47-674364_compute-text-vectors_127-0
I 03-17 18:35:47 controller.py:199] Started monitoring.
I 03-17 18:35:47 state.py:451] Launching the spot cluster...
I 03-17 18:35:48 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:35:49 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:35:49 optimizer.py:749] 
I 03-17 18:35:49 optimizer.py:884] Considered resources (1 node):
I 03-17 18:35:49 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:35:49 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:35:49 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:35:49 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:35:49 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-35-49-728674/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-35-49-728674/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:35:49 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:37:02 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:37:59 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:37:59 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:37:59 cloud_vm_ray_backend.py:2097] 
W 03-17 18:37:59 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-35-49-728674/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-35-49-728674/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:37:59 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-35-49-728674/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:38:00 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:38:00 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:38:00 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:38:00 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:38:00 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:38:00 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:38:00 recovery_strategy.py:364] Retrying to launch the cluster in 42.9 seconds.
I 03-17 18:38:44 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:38:45 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:38:45 optimizer.py:749] 
I 03-17 18:38:45 optimizer.py:884] Considered resources (1 node):
I 03-17 18:38:45 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:38:45 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:38:45 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:38:45 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:38:45 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-38-45-249767/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-38-45-249767/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:38:45 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:39:01 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:39:15 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:39:16 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:39:16 cloud_vm_ray_backend.py:2097] 
W 03-17 18:39:16 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-38-45-249767/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-38-45-249767/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:39:16 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-38-45-249767/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:39:16 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:39:16 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:39:16 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:39:16 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:39:16 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:39:16 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:39:16 recovery_strategy.py:364] Retrying to launch the cluster in 68.6 seconds.
I 03-17 18:40:26 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:40:26 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:40:26 optimizer.py:749] 
I 03-17 18:40:26 optimizer.py:884] Considered resources (1 node):
I 03-17 18:40:26 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:40:26 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:40:26 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:40:26 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:40:26 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-26-948749/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-26-948749/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:40:27 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:40:34 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:40:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:40:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:40:43 cloud_vm_ray_backend.py:2097] 
W 03-17 18:40:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-26-948749/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-26-948749/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:40:43 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-40-26-948749/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:40:43 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:40:43 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:40:43 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:40:43 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:40:43 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:40:43 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:40:43 recovery_strategy.py:364] Retrying to launch the cluster in 103.8 seconds.
I 03-17 18:42:28 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:42:29 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:42:29 optimizer.py:749] 
I 03-17 18:42:29 optimizer.py:884] Considered resources (1 node):
I 03-17 18:42:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:42:29 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:42:29 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:42:29 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:42:29 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-29-464522/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-29-464522/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:42:29 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:42:32 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:42:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:42:56 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:42:56 cloud_vm_ray_backend.py:2097] 
W 03-17 18:42:56 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-29-464522/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-29-464522/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:42:56 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-42-29-464522/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:42:56 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:42:56 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:42:56 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:42:56 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:42:56 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:42:56 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:42:56 recovery_strategy.py:364] Retrying to launch the cluster in 160.0 seconds.
I 03-17 18:45:37 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:45:38 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:45:38 optimizer.py:749] 
I 03-17 18:45:38 optimizer.py:884] Considered resources (1 node):
I 03-17 18:45:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:45:38 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:45:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:45:38 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:45:38 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-45-38-522901/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-45-38-522901/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:45:38 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:45:41 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:45:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:45:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:45:43 cloud_vm_ray_backend.py:2097] 
W 03-17 18:45:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-45-38-522901/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-45-38-522901/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:45:43 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-45-38-522901/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:45:43 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:45:43 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:45:43 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:45:43 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:45:43 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:45:43 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:45:43 recovery_strategy.py:364] Retrying to launch the cluster in 281.1 seconds.
I 03-17 18:50:25 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:50:26 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:50:26 optimizer.py:749] 
I 03-17 18:50:26 optimizer.py:884] Considered resources (1 node):
I 03-17 18:50:26 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:50:26 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:50:26 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:50:26 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:50:26 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-50-26-757044/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-50-26-757044/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:50:26 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:50:29 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:50:31 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:50:31 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:50:31 cloud_vm_ray_backend.py:2097] 
W 03-17 18:50:31 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-50-26-757044/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-50-26-757044/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:50:31 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-50-26-757044/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:50:31 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:50:31 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:50:31 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:50:31 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:50:31 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:50:31 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:50:32 recovery_strategy.py:364] Retrying to launch the cluster in 383.6 seconds.
I 03-17 18:56:56 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:56:57 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:56:57 optimizer.py:749] 
I 03-17 18:56:57 optimizer.py:884] Considered resources (1 node):
I 03-17 18:56:57 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:56:57 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:56:57 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:56:57 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:56:57 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-57-645413/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-57-645413/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:56:57 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:57:00 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:57:02 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:57:02 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:57:02 cloud_vm_ray_backend.py:2097] 
W 03-17 18:57:02 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-57-645413/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-57-645413/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:57:02 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-56-57-645413/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:57:02 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:57:02 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:57:02 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:57:02 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:57:02 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:57:02 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:57:03 recovery_strategy.py:364] Retrying to launch the cluster in 184.7 seconds.
I 03-17 19:00:08 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:00:09 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:00:09 optimizer.py:749] 
I 03-17 19:00:09 optimizer.py:884] Considered resources (1 node):
I 03-17 19:00:09 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:00:09 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:00:09 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:00:09 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:00:09 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-09-636295/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-09-636295/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:00:09 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:00:12 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:00:13 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:00:14 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:00:14 cloud_vm_ray_backend.py:2097] 
W 03-17 19:00:14 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-09-636295/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-09-636295/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:00:14 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-00-09-636295/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:00:14 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:00:14 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:00:14 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:00:14 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:00:14 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:00:14 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:00:14 recovery_strategy.py:364] Retrying to launch the cluster in 207.7 seconds.
I 03-17 19:03:43 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:03:44 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:03:44 optimizer.py:749] 
I 03-17 19:03:44 optimizer.py:884] Considered resources (1 node):
I 03-17 19:03:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:03:44 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:03:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:03:44 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:03:44 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-03-44-499707/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-03-44-499707/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:03:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:03:47 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:03:48 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:03:49 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:03:49 cloud_vm_ray_backend.py:2097] 
W 03-17 19:03:49 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-03-44-499707/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-03-44-499707/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:03:49 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-03-44-499707/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:03:49 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:03:49 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:03:49 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:03:49 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:03:49 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:03:49 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:03:50 recovery_strategy.py:364] Retrying to launch the cluster in 229.7 seconds.
I 03-17 19:07:40 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:07:41 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:07:41 optimizer.py:749] 
I 03-17 19:07:41 optimizer.py:884] Considered resources (1 node):
I 03-17 19:07:41 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:07:41 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:07:41 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:07:41 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:07:41 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-07-41-527023/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-07-41-527023/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:07:41 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:07:44 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:07:45 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:07:46 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:07:46 cloud_vm_ray_backend.py:2097] 
W 03-17 19:07:46 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-07-41-527023/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-07-41-527023/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:07:46 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-07-41-527023/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:07:46 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:07:46 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:07:46 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:07:46 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:07:46 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:07:46 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:07:46 recovery_strategy.py:364] Retrying to launch the cluster in 327.5 seconds.
I 03-17 19:13:15 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:13:16 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:13:16 optimizer.py:749] 
I 03-17 19:13:16 optimizer.py:884] Considered resources (1 node):
I 03-17 19:13:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:13:16 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:13:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:13:16 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:13:16 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-13-16-368764/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-13-16-368764/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:13:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:13:19 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:13:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:13:21 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:13:21 cloud_vm_ray_backend.py:2097] 
W 03-17 19:13:21 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-13-16-368764/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-13-16-368764/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:13:21 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-13-16-368764/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:13:21 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:13:21 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:13:21 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:13:21 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:13:21 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:13:21 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:13:22 recovery_strategy.py:364] Retrying to launch the cluster in 388.4 seconds.
I 03-17 19:19:51 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:19:52 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:19:52 optimizer.py:749] 
I 03-17 19:19:52 optimizer.py:884] Considered resources (1 node):
I 03-17 19:19:52 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:19:52 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:19:52 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:19:52 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:19:52 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-19-52-413131/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-19-52-413131/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:19:52 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:19:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:19:56 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:19:57 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:19:57 cloud_vm_ray_backend.py:2097] 
W 03-17 19:19:57 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-19-52-413131/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-19-52-413131/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:19:57 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-19-52-413131/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:19:57 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:19:57 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:19:57 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:19:57 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:19:57 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:19:57 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:19:57 recovery_strategy.py:364] Retrying to launch the cluster in 310.8 seconds.
I 03-17 19:25:09 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:25:10 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:25:10 optimizer.py:749] 
I 03-17 19:25:10 optimizer.py:884] Considered resources (1 node):
I 03-17 19:25:10 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:25:10 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:25:10 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:25:10 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:25:10 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-25-10-488536/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-25-10-488536/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:25:10 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:25:13 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:25:14 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:25:15 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:25:15 cloud_vm_ray_backend.py:2097] 
W 03-17 19:25:15 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-25-10-488536/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-25-10-488536/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:25:15 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-25-10-488536/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:25:15 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:25:15 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:25:15 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:25:15 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:25:15 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:25:15 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:25:15 recovery_strategy.py:364] Retrying to launch the cluster in 319.7 seconds.
I 03-17 19:30:36 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:30:37 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:30:37 optimizer.py:749] 
I 03-17 19:30:37 optimizer.py:884] Considered resources (1 node):
I 03-17 19:30:37 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:30:37 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:30:37 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:30:37 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:30:37 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-30-37-400508/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-30-37-400508/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:30:37 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:30:40 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:30:41 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:30:42 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:30:42 cloud_vm_ray_backend.py:2097] 
W 03-17 19:30:42 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-30-37-400508/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-30-37-400508/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:30:42 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-30-37-400508/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:30:42 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:30:42 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:30:42 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:30:42 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:30:42 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:30:42 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:30:42 recovery_strategy.py:364] Retrying to launch the cluster in 320.7 seconds.
I 03-17 19:36:04 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:36:05 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:36:05 optimizer.py:749] 
I 03-17 19:36:05 optimizer.py:884] Considered resources (1 node):
I 03-17 19:36:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:36:05 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:36:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:36:05 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:36:05 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-36-05-298388/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-36-05-298388/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:36:05 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:36:08 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:36:09 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:36:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:36:10 cloud_vm_ray_backend.py:2097] 
W 03-17 19:36:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-36-05-298388/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-36-05-298388/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:36:10 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-36-05-298388/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:36:10 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:36:10 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:36:10 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:36:10 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:36:10 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:36:10 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:36:10 recovery_strategy.py:364] Retrying to launch the cluster in 211.9 seconds.
I 03-17 19:39:43 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:39:44 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:39:44 optimizer.py:749] 
I 03-17 19:39:44 optimizer.py:884] Considered resources (1 node):
I 03-17 19:39:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:39:44 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:39:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:39:44 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:39:44 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-39-44-525761/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-39-44-525761/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:39:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:39:47 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:39:48 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:39:49 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:39:49 cloud_vm_ray_backend.py:2097] 
W 03-17 19:39:49 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-39-44-525761/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-39-44-525761/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:39:49 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-39-44-525761/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:39:49 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:39:49 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:39:49 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:39:49 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:39:49 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:39:49 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:39:49 recovery_strategy.py:364] Retrying to launch the cluster in 407.1 seconds.
I 03-17 19:46:38 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:46:38 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:46:38 optimizer.py:749] 
I 03-17 19:46:38 optimizer.py:884] Considered resources (1 node):
I 03-17 19:46:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:46:38 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:46:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:46:38 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:46:38 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-38-826057/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-38-826057/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:46:38 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:46:41 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:46:43 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:46:43 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:46:43 cloud_vm_ray_backend.py:2097] 
W 03-17 19:46:43 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-38-826057/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-38-826057/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:46:43 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-46-38-826057/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:46:43 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:46:43 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:46:43 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:46:43 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:46:43 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:46:43 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:46:44 recovery_strategy.py:364] Retrying to launch the cluster in 305.3 seconds.
I 03-17 19:51:50 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:51:51 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:51:51 optimizer.py:749] 
I 03-17 19:51:51 optimizer.py:884] Considered resources (1 node):
I 03-17 19:51:51 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:51:51 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:51:51 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:51:51 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:51:51 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-51-51-451189/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-51-51-451189/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:51:51 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:51:54 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:52:00 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:52:01 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:52:01 cloud_vm_ray_backend.py:2097] 
W 03-17 19:52:01 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-51-51-451189/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-51-51-451189/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:52:01 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-51-51-451189/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:52:01 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:52:01 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:52:01 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:52:01 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:52:01 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:52:01 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:52:01 recovery_strategy.py:364] Retrying to launch the cluster in 413.2 seconds.
I 03-17 19:53:35 controller.py:543] Cancelling managed job, job_id: 127, task_id: 0
I 03-17 19:53:35 state.py:653] Cancelling the job...
I 03-17 19:53:35 controller.py:552] Killing controller process 56094.
I 03-17 19:53:36 controller.py:560] Controller process 56094 killed.
I 03-17 19:53:36 controller.py:562] Cleaning up any cluster for job 127.
I 03-17 19:53:37 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-bkfaep4m
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-bkfaep4m[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-bkfaep4m[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-bkfaep4m[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 19:53:42 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-bkfaep4m.[0m
I 03-17 19:53:42 controller.py:571] Cluster of managed job 127 has been cleaned up.
I 03-17 19:53:42 state.py:674] Job cancelled.
