I 03-17 18:33:14 controller.py:59] DAG:
I 03-17 18:33:14 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 18:33:14 controller.py:59]   resources: AWS(cpus=4, {'L4': 1}, region=ap-northeast-2)]
I 03-17 18:33:14 controller.py:195] Submitted managed job 51 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-18-33-14-070791_compute-text-vectors_51-0
I 03-17 18:33:14 controller.py:199] Started monitoring.
I 03-17 18:33:14 state.py:451] Launching the spot cluster...
I 03-17 18:33:15 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:33:16 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:33:16 optimizer.py:749] 
I 03-17 18:33:16 optimizer.py:884] Considered resources (1 node):
I 03-17 18:33:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:33:16 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:33:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:33:16 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:33:16 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-16-171564/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-16-171564/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:33:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:33:28 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:33:29 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:33:30 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:33:30 cloud_vm_ray_backend.py:2097] 
W 03-17 18:33:30 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-16-171564/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-16-171564/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:33:30 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-33-16-171564/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:33:30 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:33:30 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:33:30 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:33:30 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:33:30 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:33:30 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:33:31 recovery_strategy.py:364] Retrying to launch the cluster in 63.1 seconds.
I 03-17 18:34:34 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:34:36 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:34:36 optimizer.py:749] 
I 03-17 18:34:36 optimizer.py:884] Considered resources (1 node):
I 03-17 18:34:36 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:34:36 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:34:36 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:34:36 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:34:36 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-35-979960/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-35-979960/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:34:36 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:36:37 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:36:44 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:36:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:36:45 cloud_vm_ray_backend.py:2097] 
W 03-17 18:36:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-35-979960/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-35-979960/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:36:45 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-34-35-979960/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:36:45 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:36:45 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:36:45 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:36:45 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:36:45 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:36:45 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:36:45 recovery_strategy.py:364] Retrying to launch the cluster in 135.7 seconds.
I 03-17 18:39:02 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:39:03 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:39:03 optimizer.py:749] 
I 03-17 18:39:03 optimizer.py:884] Considered resources (1 node):
I 03-17 18:39:03 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:39:03 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:39:03 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:39:03 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:39:03 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-39-02-961353/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-39-02-961353/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:39:03 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:39:10 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:39:18 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:39:19 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:39:19 cloud_vm_ray_backend.py:2097] 
W 03-17 18:39:19 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-39-02-961353/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-39-02-961353/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:39:19 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-39-02-961353/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:39:19 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:39:19 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:39:19 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:39:19 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:39:19 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:39:19 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:39:19 recovery_strategy.py:364] Retrying to launch the cluster in 194.3 seconds.
I 03-17 18:42:35 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:42:35 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:42:35 optimizer.py:749] 
I 03-17 18:42:35 optimizer.py:884] Considered resources (1 node):
I 03-17 18:42:35 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:42:35 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:42:35 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:42:35 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:42:35 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-35-829105/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-35-829105/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:42:35 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:42:45 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:42:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:42:56 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:42:56 cloud_vm_ray_backend.py:2097] 
W 03-17 18:42:56 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-35-829105/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-42-35-829105/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:42:56 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-42-35-829105/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:42:56 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:42:56 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:42:56 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:42:56 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:42:56 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:42:56 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:42:57 recovery_strategy.py:364] Retrying to launch the cluster in 192.2 seconds.
I 03-17 18:46:10 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:46:11 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:46:11 optimizer.py:749] 
I 03-17 18:46:11 optimizer.py:884] Considered resources (1 node):
I 03-17 18:46:11 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:46:11 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:46:11 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:46:11 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:46:11 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-46-11-092535/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-46-11-092535/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:46:11 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:46:14 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:46:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:46:21 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:46:21 cloud_vm_ray_backend.py:2097] 
W 03-17 18:46:21 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-46-11-092535/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-46-11-092535/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:46:21 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-46-11-092535/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:46:21 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:46:21 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:46:21 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:46:21 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:46:21 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:46:21 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:46:21 recovery_strategy.py:364] Retrying to launch the cluster in 202.4 seconds.
I 03-17 18:49:45 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:49:46 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:49:46 optimizer.py:749] 
I 03-17 18:49:46 optimizer.py:884] Considered resources (1 node):
I 03-17 18:49:46 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:49:46 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:49:46 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:49:46 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:49:46 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-49-46-120513/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-49-46-120513/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:49:46 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:49:49 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:49:50 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:49:50 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:49:50 cloud_vm_ray_backend.py:2097] 
W 03-17 18:49:50 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-49-46-120513/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-49-46-120513/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:49:50 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-49-46-120513/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:49:51 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:49:51 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:49:51 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:49:51 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:49:51 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:49:51 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:49:51 recovery_strategy.py:364] Retrying to launch the cluster in 408.9 seconds.
I 03-17 18:56:41 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:56:42 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:56:42 optimizer.py:749] 
I 03-17 18:56:42 optimizer.py:884] Considered resources (1 node):
I 03-17 18:56:42 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:56:42 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:56:42 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:56:42 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:56:42 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-42-232960/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-42-232960/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:56:42 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:56:45 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:56:50 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:56:51 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:56:51 cloud_vm_ray_backend.py:2097] 
W 03-17 18:56:51 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-42-232960/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-56-42-232960/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:56:51 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-56-42-232960/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:56:51 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:56:51 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:56:51 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:56:51 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:56:51 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:56:51 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:56:51 recovery_strategy.py:364] Retrying to launch the cluster in 226.0 seconds.
I 03-17 19:00:38 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:00:39 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:00:39 optimizer.py:749] 
I 03-17 19:00:39 optimizer.py:884] Considered resources (1 node):
I 03-17 19:00:39 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:00:39 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:00:39 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:00:39 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:00:39 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-39-578165/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-39-578165/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:00:39 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:00:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:00:43 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:00:44 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:00:44 cloud_vm_ray_backend.py:2097] 
W 03-17 19:00:44 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-39-578165/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-00-39-578165/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:00:44 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-00-39-578165/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:00:44 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:00:44 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:00:44 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:00:44 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:00:44 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:00:44 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:00:45 recovery_strategy.py:364] Retrying to launch the cluster in 237.6 seconds.
I 03-17 19:04:43 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:04:44 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:04:44 optimizer.py:749] 
I 03-17 19:04:44 optimizer.py:884] Considered resources (1 node):
I 03-17 19:04:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:04:44 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:04:44 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:04:44 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:04:44 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-04-44-490357/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-04-44-490357/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:04:44 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:04:47 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:04:48 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:04:49 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:04:49 cloud_vm_ray_backend.py:2097] 
W 03-17 19:04:49 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-04-44-490357/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-04-44-490357/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:04:49 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-04-44-490357/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:04:49 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:04:49 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:04:49 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:04:49 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:04:49 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:04:49 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:04:50 recovery_strategy.py:364] Retrying to launch the cluster in 419.2 seconds.
I 03-17 19:11:50 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:11:51 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:11:51 optimizer.py:749] 
I 03-17 19:11:51 optimizer.py:884] Considered resources (1 node):
I 03-17 19:11:51 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:11:51 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:11:51 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:11:51 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:11:51 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-51-031317/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-51-031317/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:11:51 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:11:54 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:11:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:11:55 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:11:55 cloud_vm_ray_backend.py:2097] 
W 03-17 19:11:55 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-51-031317/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-51-031317/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:11:55 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-11-51-031317/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:11:56 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:11:56 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:11:56 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:11:56 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:11:56 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:11:56 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:11:56 recovery_strategy.py:364] Retrying to launch the cluster in 360.3 seconds.
I 03-17 19:17:57 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:17:58 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:17:58 optimizer.py:749] 
I 03-17 19:17:58 optimizer.py:884] Considered resources (1 node):
I 03-17 19:17:58 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:17:58 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:17:58 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:17:58 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:17:58 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-17-58-539057/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-17-58-539057/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:17:58 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:18:01 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:18:02 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:18:03 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:18:03 cloud_vm_ray_backend.py:2097] 
W 03-17 19:18:03 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-17-58-539057/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-17-58-539057/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:18:03 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-17-58-539057/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:18:03 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:18:03 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:18:03 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:18:03 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:18:03 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:18:03 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:18:04 recovery_strategy.py:364] Retrying to launch the cluster in 264.6 seconds.
I 03-17 19:22:29 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:22:30 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:22:30 optimizer.py:749] 
I 03-17 19:22:30 optimizer.py:884] Considered resources (1 node):
I 03-17 19:22:30 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:22:30 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:22:30 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:22:30 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:22:30 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-22-30-421851/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-22-30-421851/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:22:30 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:22:33 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:22:34 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:22:35 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:22:35 cloud_vm_ray_backend.py:2097] 
W 03-17 19:22:35 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-22-30-421851/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-22-30-421851/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:22:35 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-22-30-421851/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:22:35 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:22:35 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:22:35 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:22:35 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:22:35 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:22:35 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:22:35 recovery_strategy.py:364] Retrying to launch the cluster in 219.3 seconds.
I 03-17 19:26:16 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:26:17 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:26:17 optimizer.py:749] 
I 03-17 19:26:17 optimizer.py:884] Considered resources (1 node):
I 03-17 19:26:17 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:26:17 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:26:17 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:26:17 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:26:17 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-17-134685/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-17-134685/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:26:17 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:26:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:26:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:26:22 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:26:22 cloud_vm_ray_backend.py:2097] 
W 03-17 19:26:22 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-17-134685/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-17-134685/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:26:22 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-26-17-134685/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:26:22 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:26:22 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:26:22 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:26:22 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:26:22 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:26:22 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:26:22 recovery_strategy.py:364] Retrying to launch the cluster in 196.2 seconds.
I 03-17 19:29:39 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:29:40 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:29:40 optimizer.py:749] 
I 03-17 19:29:40 optimizer.py:884] Considered resources (1 node):
I 03-17 19:29:40 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:29:40 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:29:40 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:29:40 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:29:40 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-29-40-727370/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-29-40-727370/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:29:40 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:29:43 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:29:45 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:29:45 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:29:45 cloud_vm_ray_backend.py:2097] 
W 03-17 19:29:45 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-29-40-727370/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-29-40-727370/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:29:45 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-29-40-727370/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:29:45 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:29:45 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:29:45 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:29:45 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:29:45 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:29:45 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:29:46 recovery_strategy.py:364] Retrying to launch the cluster in 330.7 seconds.
I 03-17 19:35:17 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:35:18 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:35:18 optimizer.py:749] 
I 03-17 19:35:18 optimizer.py:884] Considered resources (1 node):
I 03-17 19:35:18 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:35:18 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:35:18 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:35:18 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:35:18 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-35-18-756561/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-35-18-756561/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:35:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:35:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:35:23 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:35:23 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:35:23 cloud_vm_ray_backend.py:2097] 
W 03-17 19:35:23 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-35-18-756561/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-35-18-756561/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:35:23 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-35-18-756561/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:35:23 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:35:23 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:35:23 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:35:23 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:35:23 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:35:23 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:35:24 recovery_strategy.py:364] Retrying to launch the cluster in 339.8 seconds.
I 03-17 19:41:05 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:41:05 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:41:05 optimizer.py:749] 
I 03-17 19:41:05 optimizer.py:884] Considered resources (1 node):
I 03-17 19:41:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:41:05 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:41:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:41:05 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:41:05 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-41-05-907133/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-41-05-907133/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:41:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:41:09 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:41:10 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:41:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:41:10 cloud_vm_ray_backend.py:2097] 
W 03-17 19:41:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-41-05-907133/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-41-05-907133/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:41:10 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-41-05-907133/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:41:11 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:41:11 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:41:11 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:41:11 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:41:11 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:41:11 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:41:11 recovery_strategy.py:364] Retrying to launch the cluster in 292.1 seconds.
I 03-17 19:46:04 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:46:05 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:46:05 optimizer.py:749] 
I 03-17 19:46:05 optimizer.py:884] Considered resources (1 node):
I 03-17 19:46:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:46:05 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:46:05 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:46:05 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:46:05 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-05-267337/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-05-267337/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:46:05 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:46:08 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:46:09 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:46:09 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:46:09 cloud_vm_ray_backend.py:2097] 
W 03-17 19:46:09 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-05-267337/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-46-05-267337/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:46:09 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-46-05-267337/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:46:10 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:46:10 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:46:10 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:46:10 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:46:10 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:46:10 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:46:10 recovery_strategy.py:364] Retrying to launch the cluster in 280.3 seconds.
I 03-17 19:50:51 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:50:52 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:50:52 optimizer.py:749] 
I 03-17 19:50:52 optimizer.py:884] Considered resources (1 node):
I 03-17 19:50:52 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:50:52 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:50:52 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:50:52 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:50:52 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-50-52-637247/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-50-52-637247/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:50:52 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:50:55 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:50:57 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:50:57 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:50:57 cloud_vm_ray_backend.py:2097] 
W 03-17 19:50:57 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-50-52-637247/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-50-52-637247/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:50:57 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-50-52-637247/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:50:57 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:50:57 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:50:57 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:50:57 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:50:57 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:50:57 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:50:58 recovery_strategy.py:364] Retrying to launch the cluster in 244.9 seconds.
I 03-17 19:53:36 controller.py:543] Cancelling managed job, job_id: 51, task_id: 0
I 03-17 19:53:36 state.py:653] Cancelling the job...
I 03-17 19:53:36 controller.py:552] Killing controller process 31099.
I 03-17 19:53:36 controller.py:560] Controller process 31099 killed.
I 03-17 19:53:36 controller.py:562] Cleaning up any cluster for job 51.
I 03-17 19:53:37 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c7qmbf5x
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c7qmbf5x[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c7qmbf5x[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c7qmbf5x[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 19:53:43 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-c7qmbf5x.[0m
I 03-17 19:53:43 controller.py:571] Cluster of managed job 51 has been cleaned up.
I 03-17 19:53:43 state.py:674] Job cancelled.
