I 03-17 18:33:29 controller.py:59] DAG:
I 03-17 18:33:29 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 18:33:29 controller.py:59]   resources: AWS(cpus=4, {'L4': 1}, region=ap-northeast-2)]
I 03-17 18:33:29 controller.py:195] Submitted managed job 57 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-18-33-29-539053_compute-text-vectors_57-0
I 03-17 18:33:29 controller.py:199] Started monitoring.
I 03-17 18:33:29 state.py:451] Launching the spot cluster...
I 03-17 18:33:30 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:33:31 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:33:31 optimizer.py:749] 
I 03-17 18:33:31 optimizer.py:884] Considered resources (1 node):
I 03-17 18:33:31 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:33:31 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:33:31 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:33:31 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:33:31 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-31-551569/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-31-551569/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:33:31 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:33:35 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:33:36 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:33:36 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:33:36 cloud_vm_ray_backend.py:2097] 
W 03-17 18:33:36 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-31-551569/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-33-31-551569/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:33:36 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-33-31-551569/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:33:37 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:33:37 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:33:37 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:33:37 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:33:37 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:33:37 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:33:37 recovery_strategy.py:364] Retrying to launch the cluster in 58.6 seconds.
I 03-17 18:34:37 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:34:38 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:34:38 optimizer.py:749] 
I 03-17 18:34:38 optimizer.py:884] Considered resources (1 node):
I 03-17 18:34:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:34:38 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:34:38 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:34:38 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:34:38 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-38-037772/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-38-037772/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:34:38 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:34:44 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:35:04 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:35:04 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:35:04 cloud_vm_ray_backend.py:2097] 
W 03-17 18:35:04 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-38-037772/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-34-38-037772/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:35:04 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-34-38-037772/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:35:05 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:35:05 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:35:05 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:35:05 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:35:05 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:35:05 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:35:05 recovery_strategy.py:364] Retrying to launch the cluster in 83.4 seconds.
I 03-17 18:36:29 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:36:30 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:36:30 optimizer.py:749] 
I 03-17 18:36:30 optimizer.py:884] Considered resources (1 node):
I 03-17 18:36:30 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:36:30 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:36:30 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:36:30 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:36:30 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-36-30-347419/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-36-30-347419/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:36:30 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:37:13 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:37:29 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:37:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:37:29 cloud_vm_ray_backend.py:2097] 
W 03-17 18:37:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-36-30-347419/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-36-30-347419/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:37:29 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-36-30-347419/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:37:29 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:37:29 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:37:29 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:37:29 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:37:29 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:37:29 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:37:30 recovery_strategy.py:364] Retrying to launch the cluster in 149.0 seconds.
I 03-17 18:40:00 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:40:01 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:40:01 optimizer.py:749] 
I 03-17 18:40:01 optimizer.py:884] Considered resources (1 node):
I 03-17 18:40:01 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:40:01 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:40:01 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:40:01 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:40:01 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-01-075231/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-01-075231/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:40:01 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:40:04 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:40:12 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:40:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:40:12 cloud_vm_ray_backend.py:2097] 
W 03-17 18:40:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-01-075231/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-40-01-075231/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:40:12 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-40-01-075231/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:40:12 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:40:12 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:40:12 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:40:12 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:40:12 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:40:12 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:40:13 recovery_strategy.py:364] Retrying to launch the cluster in 258.5 seconds.
I 03-17 18:44:32 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:44:33 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:44:33 optimizer.py:749] 
I 03-17 18:44:33 optimizer.py:884] Considered resources (1 node):
I 03-17 18:44:33 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:44:33 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:44:33 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:44:33 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:44:33 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-44-33-560443/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-44-33-560443/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:44:33 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:44:36 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:44:43 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:44:44 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:44:44 cloud_vm_ray_backend.py:2097] 
W 03-17 18:44:44 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-44-33-560443/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-44-33-560443/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:44:44 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-44-33-560443/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:44:44 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:44:44 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:44:44 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:44:44 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:44:44 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:44:44 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:44:44 recovery_strategy.py:364] Retrying to launch the cluster in 246.9 seconds.
I 03-17 18:48:52 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:48:53 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:48:53 optimizer.py:749] 
I 03-17 18:48:53 optimizer.py:884] Considered resources (1 node):
I 03-17 18:48:53 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:48:53 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:48:53 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:48:53 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:48:53 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-48-53-697176/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-48-53-697176/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:48:53 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:48:56 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:48:58 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:48:58 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:48:58 cloud_vm_ray_backend.py:2097] 
W 03-17 18:48:58 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-48-53-697176/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-48-53-697176/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:48:58 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-48-53-697176/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:48:58 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:48:58 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:48:58 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:48:58 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:48:58 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:48:58 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:48:59 recovery_strategy.py:364] Retrying to launch the cluster in 308.4 seconds.
I 03-17 18:54:08 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 18:54:09 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 18:54:09 optimizer.py:749] 
I 03-17 18:54:09 optimizer.py:884] Considered resources (1 node):
I 03-17 18:54:09 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:54:09 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 18:54:09 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 18:54:09 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 18:54:09 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-54-09-404364/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-54-09-404364/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 18:54:09 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 18:54:18 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 18:54:24 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 18:54:25 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 18:54:25 cloud_vm_ray_backend.py:2097] 
W 03-17 18:54:25 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-54-09-404364/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-18-54-09-404364/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 18:54:25 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-18-54-09-404364/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 18:54:25 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 18:54:25 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 18:54:25 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 18:54:25 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 18:54:25 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 18:54:25 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 18:54:25 recovery_strategy.py:364] Retrying to launch the cluster in 413.3 seconds.
I 03-17 19:01:20 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:01:20 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:01:20 optimizer.py:749] 
I 03-17 19:01:20 optimizer.py:884] Considered resources (1 node):
I 03-17 19:01:20 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:01:20 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:01:20 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:01:20 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:01:20 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-01-20-943958/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-01-20-943958/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:01:21 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:01:24 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:01:25 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:01:25 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:01:25 cloud_vm_ray_backend.py:2097] 
W 03-17 19:01:25 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-01-20-943958/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-01-20-943958/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:01:25 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-01-20-943958/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:01:26 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:01:26 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:01:26 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:01:26 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:01:26 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:01:26 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:01:26 recovery_strategy.py:364] Retrying to launch the cluster in 268.7 seconds.
I 03-17 19:05:56 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:05:56 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:05:56 optimizer.py:749] 
I 03-17 19:05:56 optimizer.py:884] Considered resources (1 node):
I 03-17 19:05:56 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:05:56 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:05:56 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:05:56 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:05:56 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-05-56-952445/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-05-56-952445/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:05:57 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:05:59 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:06:01 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:06:01 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:06:01 cloud_vm_ray_backend.py:2097] 
W 03-17 19:06:01 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-05-56-952445/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-05-56-952445/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:06:01 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-05-56-952445/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:06:01 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:06:01 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:06:01 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:06:01 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:06:01 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:06:01 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:06:02 recovery_strategy.py:364] Retrying to launch the cluster in 337.4 seconds.
I 03-17 19:11:40 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:11:41 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:11:41 optimizer.py:749] 
I 03-17 19:11:41 optimizer.py:884] Considered resources (1 node):
I 03-17 19:11:41 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:11:41 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:11:41 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:11:41 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:11:41 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-41-512810/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-41-512810/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:11:41 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:11:50 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:11:51 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:11:51 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:11:51 cloud_vm_ray_backend.py:2097] 
W 03-17 19:11:51 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-41-512810/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-11-41-512810/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:11:51 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-11-41-512810/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:11:52 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:11:52 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:11:52 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:11:52 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:11:52 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:11:52 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:11:52 recovery_strategy.py:364] Retrying to launch the cluster in 203.0 seconds.
I 03-17 19:15:16 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:15:17 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:15:17 optimizer.py:749] 
I 03-17 19:15:17 optimizer.py:884] Considered resources (1 node):
I 03-17 19:15:17 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:15:17 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:15:17 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:15:17 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:15:17 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-15-17-288852/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-15-17-288852/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:15:17 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:15:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:15:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:15:22 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:15:22 cloud_vm_ray_backend.py:2097] 
W 03-17 19:15:22 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-15-17-288852/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-15-17-288852/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:15:22 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-15-17-288852/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:15:22 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:15:22 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:15:22 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:15:22 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:15:22 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:15:22 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:15:22 recovery_strategy.py:364] Retrying to launch the cluster in 291.6 seconds.
I 03-17 19:20:15 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:20:16 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:20:16 optimizer.py:749] 
I 03-17 19:20:16 optimizer.py:884] Considered resources (1 node):
I 03-17 19:20:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:20:16 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:20:16 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:20:16 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:20:16 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-20-16-100634/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-20-16-100634/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:20:16 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:20:19 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:20:20 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:20:20 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:20:20 cloud_vm_ray_backend.py:2097] 
W 03-17 19:20:20 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-20-16-100634/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-20-16-100634/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:20:20 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-20-16-100634/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:20:21 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:20:21 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:20:21 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:20:21 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:20:21 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:20:21 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:20:21 recovery_strategy.py:364] Retrying to launch the cluster in 392.1 seconds.
I 03-17 19:26:54 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:26:55 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:26:55 optimizer.py:749] 
I 03-17 19:26:55 optimizer.py:884] Considered resources (1 node):
I 03-17 19:26:55 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:26:55 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:26:55 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:26:55 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:26:55 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-55-372299/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-55-372299/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:26:55 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:26:58 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:26:59 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:27:00 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:27:00 cloud_vm_ray_backend.py:2097] 
W 03-17 19:27:00 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-55-372299/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-26-55-372299/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:27:00 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-26-55-372299/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:27:00 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:27:00 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:27:00 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:27:00 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:27:00 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:27:00 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:27:00 recovery_strategy.py:364] Retrying to launch the cluster in 287.8 seconds.
I 03-17 19:31:49 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:31:50 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:31:50 optimizer.py:749] 
I 03-17 19:31:50 optimizer.py:884] Considered resources (1 node):
I 03-17 19:31:50 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:31:50 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:31:50 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:31:50 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:31:50 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-31-50-323287/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-31-50-323287/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:31:50 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:31:53 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:31:54 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:31:54 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:31:54 cloud_vm_ray_backend.py:2097] 
W 03-17 19:31:54 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-31-50-323287/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-31-50-323287/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:31:54 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-31-50-323287/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:31:55 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:31:55 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:31:55 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:31:55 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:31:55 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:31:55 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:31:55 recovery_strategy.py:364] Retrying to launch the cluster in 356.8 seconds.
I 03-17 19:37:53 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:37:54 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:37:54 optimizer.py:749] 
I 03-17 19:37:54 optimizer.py:884] Considered resources (1 node):
I 03-17 19:37:54 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:37:54 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:37:54 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:37:54 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:37:54 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-37-54-189597/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-37-54-189597/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:37:54 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:37:57 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:37:58 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:37:58 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:37:58 cloud_vm_ray_backend.py:2097] 
W 03-17 19:37:58 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-37-54-189597/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-37-54-189597/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:37:58 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-37-54-189597/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:37:59 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:37:59 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:37:59 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:37:59 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:37:59 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:37:59 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:37:59 recovery_strategy.py:364] Retrying to launch the cluster in 317.0 seconds.
I 03-17 19:43:17 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:43:18 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:43:18 optimizer.py:749] 
I 03-17 19:43:18 optimizer.py:884] Considered resources (1 node):
I 03-17 19:43:18 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:43:18 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:43:18 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:43:18 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:43:18 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-43-18-290411/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-43-18-290411/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:43:18 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:43:21 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:43:29 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:43:29 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:43:29 cloud_vm_ray_backend.py:2097] 
W 03-17 19:43:29 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-43-18-290411/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-43-18-290411/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:43:29 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-43-18-290411/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:43:30 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:43:30 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:43:30 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:43:30 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:43:30 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:43:30 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:43:30 recovery_strategy.py:364] Retrying to launch the cluster in 275.7 seconds.
I 03-17 19:48:07 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 19:48:08 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 19:48:08 optimizer.py:749] 
I 03-17 19:48:08 optimizer.py:884] Considered resources (1 node):
I 03-17 19:48:08 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:48:08 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE      COST ($)   CHOSEN   
I 03-17 19:48:08 optimizer.py:952] -------------------------------------------------------------------------------------------
I 03-17 19:48:08 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-northeast-2   0.99       [32m   âœ”[0m     
I 03-17 19:48:08 optimizer.py:952] -------------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-48-08-174839/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-48-08-174839/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 19:48:08 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-northeast-2[0m (ap-northeast-2a,ap-northeast-2d).
[2mW 03-17 19:48:11 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2a). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2d.[0m
[2mW 03-17 19:48:12 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g6.xlarge capacity in the Availability Zone you requested (ap-northeast-2d). Our system will be working on provisioning additional capacity. You can currently get g6.xlarge capacity by not specifying an Availability Zone in your request or choosing ap-northeast-2a.[0m
W 03-17 19:48:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ap-northeast-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 19:48:12 cloud_vm_ray_backend.py:2097] 
W 03-17 19:48:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-48-08-174839/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-19-48-08-174839/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 19:48:12 cloud_vm_ray_backend.py:2904] [0m[31mâ¨¯[0m Failed to provision resources. [2mView logs: sky api logs -l sky-2025-03-17-19-48-08-174839/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 19:48:13 recovery_strategy.py:326] Failed to launch a cluster with error: sky.exceptions.ResourcesUnavailableError: [31mFailed to provision all possible launchable resources.[0m Relax the task's resource requirements: 1x AWS(cpus=4, {'L4': 1})
I 03-17 19:48:13 recovery_strategy.py:326] To keep retrying until the cluster is up, use the `--retry-until-up` flag.
I 03-17 19:48:13 recovery_strategy.py:326] Reasons for provision failures (for details, please check the log above):
I 03-17 19:48:13 recovery_strategy.py:326] Resource          Reason                                                     
I 03-17 19:48:13 recovery_strategy.py:326] AWS(g6.xlarge,    Failed to acquire resources in all zones in ap-            
I 03-17 19:48:13 recovery_strategy.py:326] {'L4': 1})        northeast-2 for {AWS(cpus=4, {'L4': 1})}.                  )
I 03-17 19:48:13 recovery_strategy.py:364] Retrying to launch the cluster in 419.4 seconds.
I 03-17 19:53:36 controller.py:543] Cancelling managed job, job_id: 57, task_id: 0
I 03-17 19:53:36 state.py:653] Cancelling the job...
I 03-17 19:53:36 controller.py:552] Killing controller process 34108.
I 03-17 19:53:36 controller.py:560] Controller process 34108 killed.
I 03-17 19:53:36 controller.py:562] Cleaning up any cluster for job 57.
I 03-17 19:53:37 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-aisu1cbd
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-aisu1cbd[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-aisu1cbd[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-aisu1cbd[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 19:53:43 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-aisu1cbd.[0m
I 03-17 19:53:43 controller.py:571] Cluster of managed job 57 has been cleaned up.
I 03-17 19:53:43 state.py:674] Job cancelled.
