I 03-17 20:21:55 controller.py:59] DAG:
I 03-17 20:21:55 controller.py:59] [Task<name=compute-text-vectors>(run='# Initialize and dow...')
I 03-17 20:21:55 controller.py:59]   resources: AWS(cpus=4, {'L4': 1})]
I 03-17 20:21:55 controller.py:195] Submitted managed job 137 (task: 0, name: 'compute-text-vectors'); SKYPILOT_TASK_ID: sky-managed-2025-03-17-20-21-55-150984_compute-text-vectors_137-0
I 03-17 20:21:55 controller.py:199] Started monitoring.
I 03-17 20:21:55 state.py:451] Launching the spot cluster...
I 03-17 20:21:55 storage.py:1058] Storage type StoreType.S3 already exists.
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 20:21:56 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:21:56 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:21:56 optimizer.py:749] 
I 03-17 20:21:56 optimizer.py:884] Considered resources (1 node):
I 03-17 20:21:56 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:21:56 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:21:56 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:21:56 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 20:21:56 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:21:56 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a,us-east-1b,us-east-1c,us-east-1d).
[2mW 03-17 20:21:58 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:21:59 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:00 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:01 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:01 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:01 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:01 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:01 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:22:01 optimizer.py:749] 
I 03-17 20:22:01 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:01 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:01 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:01 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:01 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 20:22:01 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:01 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a,us-east-2b,us-east-2c).
[2mW 03-17 20:22:04 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:05 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:11 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:12 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:12 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:12 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:12 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:12 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:22:12 optimizer.py:749] 
I 03-17 20:22:12 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:12 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:12 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 20:22:12 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:12 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a,us-west-2b,us-west-2c,us-west-2d).
[2mW 03-17 20:22:16 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:28 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:46 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:47 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:47 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:47 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:47 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:48 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:48 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:22:48 optimizer.py:749] 
I 03-17 20:22:48 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:48 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:48 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:22:48 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:22:48 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 20:22:48 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:48 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a,eu-north-1b).
[2mW 03-17 20:22:55 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:22:57 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:22:58 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:22:58 cloud_vm_ray_backend.py:2097] 
W 03-17 20:22:58 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:22:58 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:22:58 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:22:58 optimizer.py:749] 
I 03-17 20:22:58 optimizer.py:884] Considered resources (1 node):
I 03-17 20:22:58 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:22:58 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 20:22:58 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:22:58 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 20:22:58 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:22:58 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a,ca-central-1b).
[2mW 03-17 20:23:01 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:23:02 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:23:02 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:23:02 cloud_vm_ray_backend.py:2097] 
W 03-17 20:23:02 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:23:03 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:23:03 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:23:03 optimizer.py:749] 
I 03-17 20:23:03 optimizer.py:884] Considered resources (1 node):
I 03-17 20:23:03 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:23:03 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:23:03 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:23:03 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 20:23:03 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:23:03 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a,ap-south-1b).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:23:32 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log\u001b[0m</rich_update>"</sky-payload>
E 03-17 20:24:03 provisioner.py:665] [0m[31mâ¨¯[0m Failed to set up SkyPilot runtime on cluster.  [2mView logs: sky api logs -l sky-2025-03-17-20-21-55-747507/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 20:24:03 recovery_strategy.py:331] Failed to launch a cluster with error: RuntimeError: Failed to run setup commands on an instance. (exit code 1). Error: ===== stdout ===== 
I 03-17 20:24:03 recovery_strategy.py:331] # >>> conda initialize >>>
I 03-17 20:24:03 recovery_strategy.py:331] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:331] 
I 03-17 20:24:03 recovery_strategy.py:331] CondaKeyError: 'channels': 'https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com' is not in the 'channels' key of the config file
I 03-17 20:24:03 recovery_strategy.py:331] 
I 03-17 20:24:03 recovery_strategy.py:331] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:331] PATH=/home/ubuntu/miniconda3/bin:/home/ubuntu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] Traceback (most recent call last):
I 03-17 20:24:03 recovery_strategy.py:331]   File "python/ray/_raylet.pyx", line 3168, in ray._raylet.check_health
I 03-17 20:24:03 recovery_strategy.py:331]   File "python/ray/_raylet.pyx", line 580, in ray._raylet.check_status
I 03-17 20:24:03 recovery_strategy.py:331] ray.exceptions.RpcError: failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.42.113:6380: Failed to connect to remote host: Connection refused
I 03-17 20:24:03 recovery_strategy.py:331] Ray cluster is not found at 172.31.42.113:6380
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:331] 
I 03-17 20:24:03 recovery_strategy.py:331] ===== stderr =====)
I 03-17 20:24:03 recovery_strategy.py:334]   Traceback: Traceback (most recent call last):
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/recovery_strategy.py", line 280, in _launch
I 03-17 20:24:03 recovery_strategy.py:334]     execution.launch(
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 532, in launch
I 03-17 20:24:03 recovery_strategy.py:334]     return _execute(
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 311, in _execute
I 03-17 20:24:03 recovery_strategy.py:334]     handle = backend.provision(
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 437, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/backend.py", line 84, in provision
I 03-17 20:24:03 recovery_strategy.py:334]     return self._provision(task, to_provision, dryrun, stream_logs,
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2943, in _provision
I 03-17 20:24:03 recovery_strategy.py:334]     cluster_info = provisioner.post_provision_runtime_setup(
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/provisioner.py", line 659, in post_provision_runtime_setup
I 03-17 20:24:03 recovery_strategy.py:334]     return _post_provision_setup(cloud_name,
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/provisioner.py", line 504, in _post_provision_setup
I 03-17 20:24:03 recovery_strategy.py:334]     instance_setup.setup_runtime_on_cluster(
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/common.py", line 294, in wrapper
I 03-17 20:24:03 recovery_strategy.py:334]     return func(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 457, in _record
I 03-17 20:24:03 recovery_strategy.py:334]     return f(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 253, in setup_runtime_on_cluster
I 03-17 20:24:03 recovery_strategy.py:334]     _parallel_ssh_with_cache(_setup_node,
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 166, in _parallel_ssh_with_cache
I 03-17 20:24:03 recovery_strategy.py:334]     return [future.result() for future in results]
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 166, in <listcomp>
I 03-17 20:24:03 recovery_strategy.py:334]     return [future.result() for future in results]
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
I 03-17 20:24:03 recovery_strategy.py:334]     return self.__get_result()
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
I 03-17 20:24:03 recovery_strategy.py:334]     raise self._exception
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
I 03-17 20:24:03 recovery_strategy.py:334]     result = self.fn(*self.args, **self.kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/metadata_utils.py", line 45, in wrapper
I 03-17 20:24:03 recovery_strategy.py:334]     return function(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 112, in retry
I 03-17 20:24:03 recovery_strategy.py:334]     return func(*args, **kwargs)
I 03-17 20:24:03 recovery_strategy.py:334]   File "/home/ubuntu/skypilot-runtime/lib/python3.10/site-packages/sky/provision/instance_setup.py", line 247, in _setup_node
I 03-17 20:24:03 recovery_strategy.py:334]     raise RuntimeError(
I 03-17 20:24:03 recovery_strategy.py:334] RuntimeError: Failed to run setup commands on an instance. (exit code 1). Error: ===== stdout ===== 
I 03-17 20:24:03 recovery_strategy.py:334] # >>> conda initialize >>>
I 03-17 20:24:03 recovery_strategy.py:334] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:334] 
I 03-17 20:24:03 recovery_strategy.py:334] CondaKeyError: 'channels': 'https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com' is not in the 'channels' key of the config file
I 03-17 20:24:03 recovery_strategy.py:334] 
I 03-17 20:24:03 recovery_strategy.py:334] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:334] PATH=/home/ubuntu/miniconda3/bin:/home/ubuntu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] Traceback (most recent call last):
I 03-17 20:24:03 recovery_strategy.py:334]   File "python/ray/_raylet.pyx", line 3168, in ray._raylet.check_health
I 03-17 20:24:03 recovery_strategy.py:334]   File "python/ray/_raylet.pyx", line 580, in ray._raylet.check_status
I 03-17 20:24:03 recovery_strategy.py:334] ray.exceptions.RpcError: failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.42.113:6380: Failed to connect to remote host: Connection refused
I 03-17 20:24:03 recovery_strategy.py:334] Ray cluster is not found at 172.31.42.113:6380
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] curl: (22) The requested URL returned error: 500
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] bash: /home/ubuntu/.local/bin/uv: No such file or directory
I 03-17 20:24:03 recovery_strategy.py:334] 
I 03-17 20:24:03 recovery_strategy.py:334] ===== stderr =====
I 03-17 20:24:03 recovery_strategy.py:334] 
I 03-17 20:24:08 recovery_strategy.py:364] Retrying to launch the cluster in 43.2 seconds.
I 03-17 20:24:51 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c41a11jt
<sky-payload>"<rich_init>[bold cyan]Optimizing[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Optimizing[/]</rich_start>"</sky-payload>
I 03-17 20:24:52 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:24:52 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:24:52 optimizer.py:749] 
I 03-17 20:24:52 optimizer.py:884] Considered resources (1 node):
I 03-17 20:24:52 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:24:52 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:24:52 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:24:52 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-1     0.80       [32m   âœ”[0m     
I 03-17 20:24:52 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Launching[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:24:52 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-1[0m (us-east-1a,us-east-1b,us-east-1c,us-east-1d).
[2mW 03-17 20:24:59 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:00 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:01 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:25:01 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:25:01 cloud_vm_ray_backend.py:2097] 
W 03-17 20:25:01 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:25:02 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:25:02 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:25:02 optimizer.py:749] 
I 03-17 20:25:02 optimizer.py:884] Considered resources (1 node):
I 03-17 20:25:02 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:02 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:25:02 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:02 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-east-2     0.80       [32m   âœ”[0m     
I 03-17 20:25:02 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:25:02 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-east-2[0m (us-east-2a,us-east-2b,us-east-2c).
[2mW 03-17 20:25:04 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:05 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:10 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 128 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:25:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:25:10 cloud_vm_ray_backend.py:2097] 
W 03-17 20:25:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:25:11 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:25:11 optimizer.py:749] [1mEstimated cost: [0m$0.8 / hour
I 03-17 20:25:11 optimizer.py:749] 
I 03-17 20:25:11 optimizer.py:884] Considered resources (1 node):
I 03-17 20:25:11 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:11 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:25:11 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:11 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           us-west-2     0.80       [32m   âœ”[0m     
I 03-17 20:25:11 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:25:11 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS us-west-2[0m (us-west-2a,us-west-2b,us-west-2c,us-west-2d).
[2mW 03-17 20:25:14 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:49 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:54 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:25:55 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:25:55 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-west-2 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:25:55 cloud_vm_ray_backend.py:2097] 
W 03-17 20:25:55 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:25:55 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:25:55 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:25:55 optimizer.py:749] 
I 03-17 20:25:55 optimizer.py:884] Considered resources (1 node):
I 03-17 20:25:55 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:55 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:25:55 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:25:55 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           eu-north-1    0.85       [32m   âœ”[0m     
I 03-17 20:25:55 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:25:55 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS eu-north-1[0m (eu-north-1a,eu-north-1b).
[2mW 03-17 20:26:03 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:26:05 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:26:06 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in eu-north-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:26:06 cloud_vm_ray_backend.py:2097] 
W 03-17 20:26:06 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:26:06 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:26:06 optimizer.py:749] [1mEstimated cost: [0m$0.9 / hour
I 03-17 20:26:06 optimizer.py:749] 
I 03-17 20:26:06 optimizer.py:884] Considered resources (1 node):
I 03-17 20:26:06 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:26:06 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE    COST ($)   CHOSEN   
I 03-17 20:26:06 optimizer.py:952] -----------------------------------------------------------------------------------------
I 03-17 20:26:06 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ca-central-1   0.89       [32m   âœ”[0m     
I 03-17 20:26:06 optimizer.py:952] -----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:26:06 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ca-central-1[0m (ca-central-1a,ca-central-1b).
[2mW 03-17 20:26:09 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
[2mW 03-17 20:26:10 instance.py:243] create_instances: Attempt failed with An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 64 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.[0m
W 03-17 20:26:10 cloud_vm_ray_backend.py:2061] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in ca-central-1 for {AWS(cpus=4, {'L4': 1})}. 
W 03-17 20:26:10 cloud_vm_ray_backend.py:2097] 
W 03-17 20:26:10 cloud_vm_ray_backend.py:2097] [0m[33mâ†º[0m Trying other potential resources.
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Optimizing[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:26:11 optimizer.py:736] [1mTarget:[0m minimizing cost
I 03-17 20:26:11 optimizer.py:749] [1mEstimated cost: [0m$1.0 / hour
I 03-17 20:26:11 optimizer.py:749] 
I 03-17 20:26:11 optimizer.py:884] Considered resources (1 node):
I 03-17 20:26:11 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:11 optimizer.py:952]  CLOUD   INSTANCE    vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN   
I 03-17 20:26:11 optimizer.py:952] ----------------------------------------------------------------------------------------
I 03-17 20:26:11 optimizer.py:952]  AWS     g6.xlarge   4       16        L4:1           ap-south-1    0.97       [32m   âœ”[0m     
I 03-17 20:26:11 optimizer.py:952] ----------------------------------------------------------------------------------------
<sky-payload>"<rich_update>[bold cyan]Looking for resources[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:26:11 cloud_vm_ray_backend.py:1520] [0mâš™ï¸Ž Launching on AWS ap-south-1[0m (ap-south-1a,ap-south-1b).
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Waiting for SSH access[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Launching[/]</rich_start>"</sky-payload>
I 03-17 20:26:44 provisioner.py:451] [2mâ””â”€â”€ [0m[2mInstance is up.[0m
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (1/3 - initializing)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (2/3 - dependencies)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Preparing SkyPilot runtime (3/3 - runtime)[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Launching - Checking instance status[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:27:12 provisioner.py:632] [0m[32mâœ“ Cluster launched: compute-text-vectors-137.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/provision.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 20:27:12 execution.py:332] [0mâš™ï¸Ž Syncing files.
<sky-payload>"<rich_init>[bold cyan]Syncing files[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing files[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Syncing files[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Syncing file mounts[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/file_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:27:12 backend_utils.py:1315]   [2mSyncing (to 1 node): s3://skypilot-filemounts-root-726f1974-c41a11jt/job-c41a11jt/workdir -> ~/sky_workdir[0m
I 03-17 20:27:15 cloud_vm_ray_backend.py:4801] [0m[32mâœ“ Synced file_mounts.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/file_mounts.log[0m
<sky-payload>"<rich_update>[bold cyan]Mounting 1 storage[/]  \u001b[2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/storage_mounts.log\u001b[0m</rich_update>"</sky-payload>
I 03-17 20:27:15 backend_utils.py:1315]   [2mMounting (to 1 node): s3://sky-text-embeddings-multi-cluster-final -> /output[0m
I 03-17 20:27:19 cloud_vm_ray_backend.py:4892] [0m[32mâœ“ Storage mounted.[0m  [2mView logs: sky api logs -l sky-2025-03-17-20-24-52-392538/storage_mounts.log[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Running setup[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Running setup[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Running setup[/]</rich_start>"</sky-payload>
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
I 03-17 20:27:22 cloud_vm_ray_backend.py:3357] [0m[32mâœ“ Setup detached.[0m
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
<sky-payload>"<rich_init>[bold cyan]Submitting job[/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Submitting job[/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Submitting job[/]</rich_start>"</sky-payload>
I 03-17 20:27:26 cloud_vm_ray_backend.py:3460] [0mâš™ï¸Ž Job submitted, ID: 1
<sky-payload>"<rich_stop></rich_stop>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>

[?25hI 03-17 20:27:26 recovery_strategy.py:289] Managed job cluster launched.
I 03-17 20:27:30 utils.py:131] === Checking the job status... ===
I 03-17 20:27:31 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:27:31 utils.py:140] ==================================
I 03-17 20:27:32 state.py:471] Job started.
I 03-17 20:27:52 utils.py:131] === Checking the job status... ===
I 03-17 20:27:53 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:27:53 utils.py:140] ==================================
I 03-17 20:28:13 utils.py:131] === Checking the job status... ===
I 03-17 20:28:15 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:28:15 utils.py:140] ==================================
I 03-17 20:28:35 utils.py:131] === Checking the job status... ===
I 03-17 20:28:36 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:28:36 utils.py:140] ==================================
I 03-17 20:28:56 utils.py:131] === Checking the job status... ===
I 03-17 20:28:57 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:28:57 utils.py:140] ==================================
I 03-17 20:29:17 utils.py:131] === Checking the job status... ===
I 03-17 20:29:18 utils.py:137] Job status: JobStatus.SETTING_UP
I 03-17 20:29:18 utils.py:140] ==================================
I 03-17 20:29:38 utils.py:131] === Checking the job status... ===
I 03-17 20:29:40 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:29:40 utils.py:140] ==================================
I 03-17 20:30:00 utils.py:131] === Checking the job status... ===
I 03-17 20:30:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:30:01 utils.py:140] ==================================
I 03-17 20:30:21 utils.py:131] === Checking the job status... ===
I 03-17 20:30:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:30:22 utils.py:140] ==================================
I 03-17 20:30:42 utils.py:131] === Checking the job status... ===
I 03-17 20:30:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:30:44 utils.py:140] ==================================
I 03-17 20:31:04 utils.py:131] === Checking the job status... ===
I 03-17 20:31:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:31:05 utils.py:140] ==================================
I 03-17 20:31:25 utils.py:131] === Checking the job status... ===
I 03-17 20:31:27 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:31:27 utils.py:140] ==================================
I 03-17 20:31:47 utils.py:131] === Checking the job status... ===
I 03-17 20:31:48 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:31:48 utils.py:140] ==================================
I 03-17 20:32:08 utils.py:131] === Checking the job status... ===
I 03-17 20:32:09 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:32:09 utils.py:140] ==================================
I 03-17 20:32:29 utils.py:131] === Checking the job status... ===
I 03-17 20:32:30 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:32:30 utils.py:140] ==================================
I 03-17 20:32:51 utils.py:131] === Checking the job status... ===
I 03-17 20:32:52 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:32:52 utils.py:140] ==================================
I 03-17 20:33:12 utils.py:131] === Checking the job status... ===
I 03-17 20:33:14 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:33:14 utils.py:140] ==================================
I 03-17 20:33:34 utils.py:131] === Checking the job status... ===
I 03-17 20:33:37 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:33:37 utils.py:140] ==================================
I 03-17 20:33:57 utils.py:131] === Checking the job status... ===
I 03-17 20:34:01 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:01 utils.py:140] ==================================
I 03-17 20:34:21 utils.py:131] === Checking the job status... ===
I 03-17 20:34:22 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:22 utils.py:140] ==================================
I 03-17 20:34:43 utils.py:131] === Checking the job status... ===
I 03-17 20:34:44 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:34:44 utils.py:140] ==================================
I 03-17 20:35:04 utils.py:131] === Checking the job status... ===
I 03-17 20:35:05 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:05 utils.py:140] ==================================
I 03-17 20:35:25 utils.py:131] === Checking the job status... ===
I 03-17 20:35:26 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:26 utils.py:140] ==================================
I 03-17 20:35:46 utils.py:131] === Checking the job status... ===
I 03-17 20:35:47 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:35:47 utils.py:140] ==================================
I 03-17 20:36:07 utils.py:131] === Checking the job status... ===
I 03-17 20:36:08 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:08 utils.py:140] ==================================
I 03-17 20:36:28 utils.py:131] === Checking the job status... ===
I 03-17 20:36:29 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:29 utils.py:140] ==================================
I 03-17 20:36:49 utils.py:131] === Checking the job status... ===
I 03-17 20:36:50 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:36:50 utils.py:140] ==================================
I 03-17 20:37:10 utils.py:131] === Checking the job status... ===
I 03-17 20:37:11 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:11 utils.py:140] ==================================
I 03-17 20:37:31 utils.py:131] === Checking the job status... ===
I 03-17 20:37:33 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:33 utils.py:140] ==================================
I 03-17 20:37:53 utils.py:131] === Checking the job status... ===
I 03-17 20:37:54 utils.py:137] Job status: JobStatus.RUNNING
I 03-17 20:37:54 utils.py:140] ==================================
I 03-17 20:38:14 utils.py:131] === Checking the job status... ===
I 03-17 20:38:15 utils.py:137] Job status: JobStatus.SUCCEEDED
I 03-17 20:38:15 utils.py:140] ==================================
I 03-17 20:38:16 state.py:561] Job succeeded.
I 03-17 20:38:16 controller.py:238] Managed job 137 (task: 0) SUCCEEDED. Cleaning up the cluster compute-text-vectors-137.
E 03-17 20:38:19 controller_utils.py:376] Failed to find the logs for the user program at ~/sky_logs/managed_jobs/sky-2025-03-17-20-24-52-392538/run.log.
I 03-17 20:38:19 controller.py:117] 
I 03-17 20:38:19 controller.py:117] == End of logs (ID: 137) ==
I 03-17 20:38:27 state.py:656] Cancellation skipped, job is already terminal
I 03-17 20:38:27 state.py:677] Cancellation skipped, job is not CANCELLING
I 03-17 20:38:29 controller.py:552] Killing controller process 67619.
I 03-17 20:38:29 controller.py:560] Controller process 67619 killed.
I 03-17 20:38:29 controller.py:562] Cleaning up any cluster for job 137.
I 03-17 20:38:30 storage.py:699] Verifying bucket for storage skypilot-filemounts-root-726f1974-c41a11jt
<sky-payload>"<rich_init>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c41a11jt[/][/]</rich_init>"</sky-payload>
<sky-payload>"<rich_update>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c41a11jt[/][/]</rich_update>"</sky-payload>
<sky-payload>"<rich_start>[bold cyan]Deleting S3 bucket [green]skypilot-filemounts-root-726f1974-c41a11jt[/][/]</rich_start>"</sky-payload>
<sky-payload>"<rich_exit></rich_exit>"</sky-payload>
I 03-17 20:38:31 storage.py:1505] [32mDeleted S3 bucket skypilot-filemounts-root-726f1974-c41a11jt.[0m
I 03-17 20:38:31 controller.py:571] Cluster of managed job 137 has been cleaned up.
